### ISSUE TITLE
Exception handling and formatting of data

### ISSUE THREAD

**Issue by romanchyla** [adsabs/graphics_service#25]
I'm integrating Alex's impl of the graphics service, so I took look at the python part to understand what it does and noticed few things:

 - the too-permissive usage of try...catch Exception - it would be better, when possible, to use the specific exception instead of general one; eg in utils.graphics the error can be because of parsing json, but the code assumes it is because of the database connection

 - the graphics service is formatting data into html (ie. `<div><img/></div>`) - this would be best left to the client; bumblebee would be happier to receive just the data

 - unit tests are missing

**Comment by ehenneken** [comment]
@romanchyla I will work on implementing your first suggestion and I'll revise how the data is stored (I think there is some data there that doesn't get used).

I have implemented unit tests and Travis

**Comment by ehenneken** [comment]
Better exception handling has been implemented (making the distinction between JSON problems and PostgreSQL problems)

**Comment by romanchyla** [comment]
what is the implication for bumblebee? which codes will be raised in what situation? you can point me to the code, i'll get the rest there

**Comment by romanchyla** [comment]
ah, i see it (been reading my emails from top down :))

**Comment by romanchyla** [comment]
ok, so from what i understand, you are now distinguishing more error cases - but globally, the behaviour remains the same; it returns 404 for all of them; therefore bumblebee will have to deal with (what I consider 'permissible request for empty data' in a fail handler - but we have talked about that in other context and not in this issue; so I'm not going to open it again)

and how about the second suggestion? what is the rationale to have the html formatting in the code?

**Comment by ehenneken** [comment]
the HTML was in the attribute 'widget' of the output, which wasn't used anywhere, so it has been removed
